project: 
  type: website
  
website: 
  page-navigation: true
  title: "Book of abstracts, Swedish Bioinformatics Workshop 2024" 
  site-url: "https://www.sbw2024.org/" 
  repo-url: https://github.com/openscapes/quarto-website-tutorial 
  repo-actions: [edit, issue]
  
  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy; CC-By SBW2024, 2024"
    
  sidebar:
    logo: "images/SBW2024_logo_pink_final.png"
    pinned: true
    align: center
    tools: 
      - icon: globe
        href: https://www.sbw2024.org/
        text: "Swedish Bioinformatics Workshop 2024"
      - icon: github
        href: https://www.sbw2024.org/
        text: "Book of Abstracts"        

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Welcome
      - href: schedule1.qmd
        text: Schedule Monday Nov 4th
      - href: schedule2.qmd
        text: Schedule Tuesday Nov 5th
      - href: abstracts.qmd
        text: Abstracts
      - href: useful_information.qmd
        text: Useful Information



format:
  html:
    embed-resources: true
    theme:
      light: [flatly] # from https://github.com/sta210-s22/website/blob/main/_quarto.yml
      dark: [darkly]
    code-copy: true
    code-overflow: wrap
    toc: true


filters:
  - quarto

  
